# Generated by Django 3.1.2 on 2020-12-14 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201119_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_Img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[myapp.models.validate_price]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 14, 21, 36, 14, 361015, tzinfo=utc), null=True),
        ),
    ]
