# Generated by Django 3.1.2 on 2020-12-15 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201214_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_Img',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 15, 4, 49, 19, 615440, tzinfo=utc), null=True),
        ),
    ]
